service: ""
project: ipaffs
environment: dev

azure:
  location: uksouth

database:
  enabled: false
  databaseNames: []

redis:
  enabled: false

serviceBus:
  enabled: false

secretStore:
  name: "external-secrets-azure"

externalSecret:
  enabled: false
  refreshInterval: ""
  secrets: []

# vim: set ts=2 sts=2 sw=2 et:
